"use client";
import {useEffect,useState} from 'react';

export default function Notebook(){const [storageKey,setStorageKey]=useState('os-joe-notebook-v1');const [title,setTitle]=useState('My idea');const [body,setBody]=useState('');const [status,setStatus]=useState('');const [ready,setReady]=useState(false);
useEffect(()=>{const project=new URLSearchParams(location.search).get('project');const key='os-joe-notebook-v1-'+(project||'general');setStorageKey(key);if(project)setTitle(project);try{const raw=localStorage.getItem(key);if(raw){const d=JSON.parse(raw);if(typeof d.title==='string')setTitle(d.title);if(typeof d.body==='string')setBody(d.body)}}catch{setStatus('This browser could not open the saved draft.')}setReady(true)},[]);
useEffect(()=>{if(!ready)return;try{localStorage.setItem(storageKey,JSON.stringify({title,body}));setStatus('Saved on this device.')}catch{setStatus('Could not save on this device. Download your writing to keep it.')}},[title,body,ready,storageKey]);
useEffect(()=>{const mc=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!mc)return;const c=new AbortController();try{mc.registerTool({name:'read_joe_draft',description:'Read the current device-local notebook draft without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return {title,body}}},{signal:c.signal})}catch{}return()=>c.abort()},[title,body]);
function download(){const url=URL.createObjectURL(new Blob([title+'\n\n'+body],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='joe-my-writing.txt';a.click();URL.revokeObjectURL(url)}
return <main className="joe-page"><span className="system-code">03 / MY NOTEBOOK</span><h1>One idea at a time.</h1><p>Say it out loud first if you want. Then try one sentence.</p><section className="joe-panel"><label htmlFor="title">What are you working on?</label><input id="title" value={title} maxLength={120} onChange={e=>setTitle(e.target.value)}/><label htmlFor="words">Your words</label><textarea id="words" value={body} onChange={e=>setBody(e.target.value)} placeholder="My drink is… / I chose… because… / First, I…"/><p role="status">{status}</p><button className="game-button" onClick={download}>Download my writing</button><details><summary>Help me start</summary><p>What is it? Choose one detail. What would you like to change?</p><p>Try: “I chose ___ because ___.”</p></details></section></main>}
